openapi: 3.2.0
info:
  version: 0.1.87
  title: Blockfrost.io ~ API Documentation Cardano » Metadata API
  x-logo:
    url: https://staging.blockfrost.io/images/logo.svg
    altText: Blockfrost
  contact:
    name: Blockfrost Team
    url: https://blockfrost.io
    email: contact@blockfrost.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://blockfrost.io/terms
  description: Blockfrost is an API as a service that allows users to interact with the Cardano blockchain, Midnight blockchain, and parts of their ecosystems.
servers:
- url: https://cardano-mainnet.blockfrost.io/api/v0
  description: Cardano Mainnet network
- url: https://cardano-preprod.blockfrost.io/api/v0
  description: Cardano Preprod network
- url: https://cardano-preview.blockfrost.io/api/v0
  description: Cardano Preview network
- url: https://localhost:3000
  description: local
security:
- project_id: []
tags:
- name: Cardano » Metadata
paths:
  /metadata/txs/labels:
    get:
      tags:
      - Cardano » Metadata
      summary: Blockfrost Transaction Metadata Labels
      description: List of all used transaction metadata labels.
      parameters:
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the account metadata content in CBOR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tx_metadata_labels'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getMetadataTxsLabels
      x-operation-id-source: derived
  /metadata/txs/labels/{label}:
    get:
      tags:
      - Cardano » Metadata
      summary: Blockfrost Transaction Metadata Content in JSON
      description: Transaction metadata per label.
      parameters:
      - in: path
        name: label
        required: true
        schema:
          type: string
        description: Metadata label
        example: '1990'
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the account metadata content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tx_metadata_label_json'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getMetadataTxsLabelsByLabel
      x-operation-id-source: derived
  /metadata/txs/labels/{label}/cbor:
    get:
      tags:
      - Cardano » Metadata
      summary: Blockfrost Transaction Metadata Content in CBOR
      description: Transaction metadata per label.
      parameters:
      - in: path
        name: label
        required: true
        schema:
          type: string
        description: Metadata label
        example: '1990'
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the account metadata content in CBOR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tx_metadata_label_cbor'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getMetadataTxsLabelsByLabelCbor
      x-operation-id-source: derived
components:
  schemas:
    tx_metadata_labels:
      type: array
      items:
        type: object
        properties:
          label:
            type: string
            description: Metadata label
          cip10:
            type:
            - string
            - 'null'
            description: CIP10 defined description
          count:
            type: string
            description: The count of metadata entries with a specific label
        required:
        - label
        - cip10
        - count
      example:
      - label: '1990'
        cip10: null
        count: '1'
      - label: '1967'
        cip10: nut.link metadata oracles registry
        count: '3'
      - label: '1968'
        cip10: nut.link metadata oracles data points
        count: '16321'
    tx_metadata_label_cbor:
      type: array
      items:
        type: object
        properties:
          tx_hash:
            type: string
            description: Transaction hash that contains the specific metadata
          cbor_metadata:
            deprecated: true
            type:
            - string
            - 'null'
            description: Content of the CBOR metadata
          metadata:
            type:
            - string
            - 'null'
            description: Content of the CBOR metadata in hex
        required:
        - tx_hash
        - cbor_metadata
        - metadata
      example:
      - tx_hash: 257d75c8ddb0434e9b63e29ebb6241add2b835a307aa33aedba2effe09ed4ec8
        cbor_metadata: null
        metadata: null
      - tx_hash: e865f2cc01ca7381cf98dcdc4de07a5e8674b8ea16e6a18e3ed60c186fde2b9c
        cbor_metadata: null
        metadata: null
      - tx_hash: 4237501da3cfdd53ade91e8911e764bd0699d88fd43b12f44a1f459b89bc91be
        cbor_metadata: \xa100a16b436f6d62696e6174696f6e8601010101010c
        metadata: a100a16b436f6d62696e6174696f6e8601010101010c
    tx_metadata_label_json:
      type: array
      items:
        type: object
        properties:
          tx_hash:
            type: string
            description: Transaction hash that contains the specific metadata
          json_metadata:
            anyOf:
            - type: string
            - type: object
              additionalProperties: true
            - type: array
              items: {}
            - type: integer
            - type: number
            - type: boolean
            - type: 'null'
            description: Content of the JSON metadata
        required:
        - tx_hash
        - json_metadata
      example:
      - tx_hash: 257d75c8ddb0434e9b63e29ebb6241add2b835a307aa33aedba2effe09ed4ec8
        json_metadata:
          ADAUSD:
          - value: '0.10409800535729975'
            source: ergoOracles
      - tx_hash: e865f2cc01ca7381cf98dcdc4de07a5e8674b8ea16e6a18e3ed60c186fde2b9c
        json_metadata:
          ADAUSD:
          - value: '0.15409850555139935'
            source: ergoOracles
      - tx_hash: 4237501da3cfdd53ade91e8911e764bd0699d88fd43b12f44a1f459b89bc91be
        json_metadata: null
  responses:
    '403':
      description: Authentication secret is missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 403
              error:
                type: string
                example: Forbidden
              message:
                type: string
                example: Invalid project token.
            required:
            - error
            - message
            - status_code
    '429':
      description: Usage limit reached
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 429
              error:
                type: string
                example: Project Over Limit
              message:
                type: string
                example: Usage is over limit.
            required:
            - error
            - message
            - status_code
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 400
              error:
                type: string
                example: Bad Request
              message:
                type: string
                example: Backend did not understand your request.
            required:
            - error
            - message
            - status_code
    '404':
      description: Component not found
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 404
              error:
                type: string
                example: Not Found
              message:
                type: string
                example: The requested component has not been found.
            required:
            - error
            - message
            - status_code
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 500
              error:
                type: string
                example: Internal Server Error
              message:
                type: string
                example: An unexpected response was received from the backend.
            required:
            - error
            - message
            - status_code
    '418':
      description: IP has been auto-banned for extensive sending of requests after usage limit has been reached
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 418
              error:
                type: string
                example: Requested Banned
              message:
                type: string
                example: IP has been auto-banned for flooding.
            required:
            - error
            - message
            - status_code
  securitySchemes:
    project_id:
      type: apiKey
      in: header
      name: project_id
      description: 'There are multiple token types available based on network you choose

        when creating a Blockfrost a project, for a list of token types

        see available networks.

        '
