openapi: 3.2.0
info:
  version: 0.1.87
  title: Blockfrost.io ~ API Documentation Nut.link API
  x-logo:
    url: https://staging.blockfrost.io/images/logo.svg
    altText: Blockfrost
  contact:
    name: Blockfrost Team
    url: https://blockfrost.io
    email: contact@blockfrost.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://blockfrost.io/terms
  description: Blockfrost is an API as a service that allows users to interact with the Cardano blockchain, Midnight blockchain, and parts of their ecosystems.
servers:
- url: https://cardano-mainnet.blockfrost.io/api/v0
  description: Cardano Mainnet network
- url: https://cardano-preprod.blockfrost.io/api/v0
  description: Cardano Preprod network
- url: https://cardano-preview.blockfrost.io/api/v0
  description: Cardano Preview network
- url: https://localhost:3000
  description: local
security:
- project_id: []
tags:
- name: Nut.link
paths:
  /nutlink/{address}:
    get:
      tags:
      - Nut.link
      summary: Blockfrost Specific Nut.link Address
      description: List metadata about specific address
      parameters:
      - in: path
        required: true
        name: address
        schema:
          type: string
          description: Address of a metadata oracle
      responses:
        '200':
          description: Return the metadata about metadata oracle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nutlink_address'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getNutlinkByAddress
      x-operation-id-source: derived
  /nutlink/{address}/tickers:
    get:
      tags:
      - Nut.link
      summary: Blockfrost List of Tickers of an Oracle
      description: List of records of a specific oracle
      parameters:
      - in: path
        required: true
        name: address
        schema:
          type: string
          description: Address of a metadata oracle
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the tickers provided by the metadata oracle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nutlink_address_tickers'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getNutlinkByAddressTickers
      x-operation-id-source: derived
  /nutlink/{address}/tickers/{ticker}:
    get:
      tags:
      - Nut.link
      summary: Blockfrost Specific Ticker for an Address
      description: List of records of a specific ticker
      parameters:
      - in: path
        required: true
        name: address
        schema:
          type: string
          description: Address of a metadata oracle
      - in: path
        required: true
        name: ticker
        schema:
          type: string
          description: Ticker for the pool record
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the tickers provided by the metadata oracle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nutlink_address_ticker'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getNutlinkByAddressTickersByTicker
      x-operation-id-source: derived
  /nutlink/tickers/{ticker}:
    get:
      tags:
      - Nut.link
      summary: Blockfrost Specific Ticker
      description: List of records of a specific ticker
      parameters:
      - in: path
        required: true
        name: ticker
        schema:
          type: string
          description: Ticker for the pool record
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the tickers provided by the metadata oracle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nutlink_tickers_ticker'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getNutlinkTickersByTicker
      x-operation-id-source: derived
components:
  responses:
    '403':
      description: Authentication secret is missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 403
              error:
                type: string
                example: Forbidden
              message:
                type: string
                example: Invalid project token.
            required:
            - error
            - message
            - status_code
    '429':
      description: Usage limit reached
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 429
              error:
                type: string
                example: Project Over Limit
              message:
                type: string
                example: Usage is over limit.
            required:
            - error
            - message
            - status_code
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 400
              error:
                type: string
                example: Bad Request
              message:
                type: string
                example: Backend did not understand your request.
            required:
            - error
            - message
            - status_code
    '404':
      description: Component not found
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 404
              error:
                type: string
                example: Not Found
              message:
                type: string
                example: The requested component has not been found.
            required:
            - error
            - message
            - status_code
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 500
              error:
                type: string
                example: Internal Server Error
              message:
                type: string
                example: An unexpected response was received from the backend.
            required:
            - error
            - message
            - status_code
    '418':
      description: IP has been auto-banned for extensive sending of requests after usage limit has been reached
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 418
              error:
                type: string
                example: Requested Banned
              message:
                type: string
                example: IP has been auto-banned for flooding.
            required:
            - error
            - message
            - status_code
  schemas:
    nutlink_address_ticker:
      type: array
      items:
        type: object
        properties:
          tx_hash:
            type: string
            description: Hash of the transaction
          block_height:
            type: integer
            description: Block height of the record
          tx_index:
            type: integer
            description: Transaction index within the block
          payload:
            anyOf:
            - type: string
            - type: object
            - type: array
              items: {}
            - type: integer
            - type: number
            - type: boolean
            additionalProperties: true
            description: Content of the ticker
        required:
        - tx_hash
        - tx_index
        - block_height
        - payload
      example:
      - tx_hash: e8073fd5318ff43eca18a852527166aa8008bee9ee9e891f585612b7e4ba700b
        block_height: 2657092
        tx_index: 8
        payload:
        - source: coinGecko
          value: '1.29'
        - source: cryptoCompare
          value: '1.283'
    nutlink_address:
      type: object
      properties:
        address:
          type: string
          description: Bech32 encoded address
          example: addr1qxqs59lphg8g6qndelq8xwqn60ag3aeyfcp33c2kdp46a09re5df3pzwwmyq946axfcejy5n4x0y99wqpgtp2gd0k09qsgy6pz
        metadata_url:
          type: string
          description: URL of the specific metadata file
          example: https://nut.link/metadata.json
        metadata_hash:
          type: string
          description: Hash of the metadata file
          example: 6bf124f217d0e5a0a8adb1dbd8540e1334280d49ab861127868339f43b3948af
        metadata:
          type:
          - object
          - 'null'
          description: The cached metadata of the `metadata_url` file.
          additionalProperties: true
      required:
      - address
      - metadata_url
      - metadata_hash
      - metadata
    nutlink_tickers_ticker:
      type: array
      items:
        type: object
        properties:
          address:
            type: string
            description: Address of a metadata oracle
          tx_hash:
            type: string
            description: Hash of the transaction
          block_height:
            type: integer
            description: Block height of the record
          tx_index:
            type: integer
            description: Transaction index within the block
          payload:
            anyOf:
            - type: string
            - type: object
            - type: array
              items: {}
            - type: integer
            - type: number
            - type: boolean
            additionalProperties: true
            description: Content of the ticker
        required:
        - address
        - tx_hash
        - block_height
        - tx_index
        - payload
      example:
      - address: addr_test1qpmtp5t0t5y6cqkaz7rfsyrx7mld77kpvksgkwm0p7en7qum7a589n30e80tclzrrnj8qr4qvzj6al0vpgtnmrkkksnqd8upj0
        tx_hash: e8073fd5318ff43eca18a852527166aa8008bee9ee9e891f585612b7e4ba700b
        block_height: 2657092
        tx_index: 8
        payload:
        - source: coinGecko
          value: '1.29'
        - source: cryptoCompare
          value: '1.283'
    nutlink_address_tickers:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            description: Name of the ticker
          count:
            type: integer
            description: Number of ticker records
          latest_block:
            type: integer
            description: Block height of the latest record
        required:
        - name
        - count
        - latest_block
      example:
      - name: ADAUSD
        count: 1980038
        latest_block: 2657092
      - name: ADAEUR
        count: 1980038
        latest_block: 2657092
      - name: ADABTC
        count: 1980038
        latest_block: 2657092
  securitySchemes:
    project_id:
      type: apiKey
      in: header
      name: project_id
      description: 'There are multiple token types available based on network you choose

        when creating a Blockfrost a project, for a list of token types

        see available networks.

        '
