openapi: 3.2.0
info:
  version: 0.1.87
  title: Blockfrost.io ~ API Documentation Cardano » Accounts API
  x-logo:
    url: https://staging.blockfrost.io/images/logo.svg
    altText: Blockfrost
  contact:
    name: Blockfrost Team
    url: https://blockfrost.io
    email: contact@blockfrost.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://blockfrost.io/terms
  description: Blockfrost is an API as a service that allows users to interact with the Cardano blockchain, Midnight blockchain, and parts of their ecosystems.
servers:
- url: https://cardano-mainnet.blockfrost.io/api/v0
  description: Cardano Mainnet network
- url: https://cardano-preprod.blockfrost.io/api/v0
  description: Cardano Preprod network
- url: https://cardano-preview.blockfrost.io/api/v0
  description: Cardano Preview network
- url: https://localhost:3000
  description: local
security:
- project_id: []
tags:
- name: Cardano » Accounts
paths:
  /accounts/{stake_address}:
    get:
      tags:
      - Cardano » Accounts
      summary: Blockfrost Specific Account Address
      description: Obtain information about a specific stake account.
      parameters:
      - in: path
        name: stake_address
        required: true
        schema:
          type: string
        description: Bech32 stake address.
        example: stake1u9ylzsgxaa6xctf4juup682ar3juj85n8tx3hthnljg47zctvm3rc
      responses:
        '200':
          description: Return the account content.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account_content'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getAccountsByStakeAddress
      x-operation-id-source: derived
  /accounts/{stake_address}/rewards:
    get:
      tags:
      - Cardano » Accounts
      summary: Blockfrost Account Reward History
      description: Obtain information about the reward history of a specific account.
      parameters:
      - in: path
        name: stake_address
        required: true
        schema:
          type: string
        description: Bech32 stake address.
        example: stake1u9ylzsgxaa6xctf4juup682ar3juj85n8tx3hthnljg47zctvm3rc
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the account content.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account_reward_content'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getAccountsByStakeAddressRewards
      x-operation-id-source: derived
  /accounts/{stake_address}/history:
    get:
      tags:
      - Cardano » Accounts
      summary: Blockfrost Account History
      description: Obtain information about the history of a specific account.
      parameters:
      - in: path
        name: stake_address
        required: true
        schema:
          type: string
        description: Bech32 stake address.
        example: stake1u9ylzsgxaa6xctf4juup682ar3juj85n8tx3hthnljg47zctvm3rc
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the account content.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account_history_content'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getAccountsByStakeAddressHistory
      x-operation-id-source: derived
  /accounts/{stake_address}/delegations:
    get:
      tags:
      - Cardano » Accounts
      summary: Blockfrost Account Delegation History
      description: Obtain information about the delegation of a specific account.
      parameters:
      - in: path
        name: stake_address
        required: true
        schema:
          type: string
        description: Bech32 stake address.
        example: stake1u9ylzsgxaa6xctf4juup682ar3juj85n8tx3hthnljg47zctvm3rc
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the account delegations content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account_delegation_content'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getAccountsByStakeAddressDelegations
      x-operation-id-source: derived
  /accounts/{stake_address}/registrations:
    get:
      tags:
      - Cardano » Accounts
      summary: Blockfrost Account Registration History
      description: Obtain information about the registrations and deregistrations of a specific account.
      parameters:
      - in: path
        name: stake_address
        required: true
        schema:
          type: string
        description: Bech32 stake address.
        example: stake1u9ylzsgxaa6xctf4juup682ar3juj85n8tx3hthnljg47zctvm3rc
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the account registration content.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account_registration_content'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getAccountsByStakeAddressRegistrations
      x-operation-id-source: derived
  /accounts/{stake_address}/withdrawals:
    get:
      tags:
      - Cardano » Accounts
      summary: Blockfrost Account Withdrawal History
      description: Obtain information about the withdrawals of a specific account.
      parameters:
      - in: path
        name: stake_address
        required: true
        schema:
          type: string
        description: Bech32 stake address.
        example: stake1u9ylzsgxaa6xctf4juup682ar3juj85n8tx3hthnljg47zctvm3rc
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the account withdrawal content.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account_withdrawal_content'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getAccountsByStakeAddressWithdrawals
      x-operation-id-source: derived
  /accounts/{stake_address}/mirs:
    get:
      tags:
      - Cardano » Accounts
      summary: Blockfrost Account MIR History
      description: Obtain information about the MIRs of a specific account.
      parameters:
      - in: path
        name: stake_address
        required: true
        schema:
          type: string
        description: Bech32 stake address.
        example: stake1u9ylzsgxaa6xctf4juup682ar3juj85n8tx3hthnljg47zctvm3rc
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the account MIR content.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account_mir_content'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getAccountsByStakeAddressMirs
      x-operation-id-source: derived
  /accounts/{stake_address}/addresses:
    get:
      tags:
      - Cardano » Accounts
      summary: Blockfrost Account Associated Addresses
      description: 'Obtain information about the addresses of a specific account.

        Be careful, as an account could be part of a mangled address and does not necessarily mean the addresses are owned by user as the account.'
      parameters:
      - in: path
        name: stake_address
        required: true
        schema:
          type: string
        description: Bech32 stake address.
        example: stake1u9ylzsgxaa6xctf4juup682ar3juj85n8tx3hthnljg47zctvm3rc
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the account addresses content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account_addresses_content'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getAccountsByStakeAddressAddresses
      x-operation-id-source: derived
  /accounts/{stake_address}/addresses/assets:
    get:
      tags:
      - Cardano » Accounts
      summary: Blockfrost Assets Associated with the Account Addresses
      description: 'Obtain information about assets associated with addresses of a specific account.

        Be careful, as an account could be part of a mangled address and does not necessarily mean the addresses are owned by user as the account.'
      parameters:
      - in: path
        name: stake_address
        required: true
        schema:
          type: string
        description: Bech32 stake address.
        example: stake1u9ylzsgxaa6xctf4juup682ar3juj85n8tx3hthnljg47zctvm3rc
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the account addresses content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account_addresses_assets'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getAccountsByStakeAddressAddressesAssets
      x-operation-id-source: derived
  /accounts/{stake_address}/addresses/total:
    get:
      tags:
      - Cardano » Accounts
      summary: Blockfrost Detailed Information About Account Associated Addresses
      description: 'Obtain summed details about all addresses associated with a given account.

        Be careful, as an account could be part of a mangled address and does not necessarily mean the addresses are owned by user as the account.'
      parameters:
      - in: path
        name: stake_address
        required: true
        schema:
          type: string
        description: Bech32 address.
        example: addr1qxqs59lphg8g6qndelq8xwqn60ag3aeyfcp33c2kdp46a09re5df3pzwwmyq946axfcejy5n4x0y99wqpgtp2gd0k09qsgy6pz
      responses:
        '200':
          description: Return the Address details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account_addresses_total'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getAccountsByStakeAddressAddressesTotal
      x-operation-id-source: derived
  /accounts/{stake_address}/utxos:
    get:
      tags:
      - Cardano » Accounts
      summary: Blockfrost Account UTXOs
      description: UTXOs associated with the account.
      parameters:
      - in: path
        name: stake_address
        required: true
        schema:
          type: string
        description: Bech32 stake address.
        example: stake1u9ylzsgxaa6xctf4juup682ar3juj85n8tx3hthnljg47zctvm3rc
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of results displayed on one page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      responses:
        '200':
          description: Return the account UTXOs content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account_utxo_content'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getAccountsByStakeAddressUtxos
      x-operation-id-source: derived
  /accounts/{stake_address}/transactions:
    get:
      tags:
      - Cardano » Accounts
      summary: Blockfrost Account Transactions
      description: Transactions associated with the stake address.
      parameters:
      - in: path
        name: stake_address
        required: true
        schema:
          type: string
        description: Bech32 stake address.
        example: stake1u9ylzsgxaa6xctf4juup682ar3juj85n8tx3hthnljg47zctvm3rc
      - in: query
        name: count
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 100
        description: The number of transactions per page.
      - in: query
        name: page
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 21474836
          default: 1
        description: The page number for listing the results.
      - in: query
        name: order
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
        description: 'The ordering of items from the point of view of the blockchain,

          not the page listing itself. By default, we return oldest first, newest last.

          '
      - in: query
        name: from
        required: false
        schema:
          type: string
        description: 'The block number and optionally also index from which (inclusive) to start search for results, concatenated using colon.

          Has to be lower than or equal to `to` parameter.

          '
        example: '8929261'
      - in: query
        name: to
        required: false
        schema:
          type: string
        description: 'The block number and optionally also index where (inclusive) to end the search for results, concatenated using colon.

          Has to be higher than or equal to `from` parameter.

          '
        example: '9999269:10'
      responses:
        '200':
          description: Return the list of account transactions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account_transactions_content'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '418':
          $ref: '#/components/responses/418'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getAccountsByStakeAddressTransactions
      x-operation-id-source: derived
components:
  responses:
    '403':
      description: Authentication secret is missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 403
              error:
                type: string
                example: Forbidden
              message:
                type: string
                example: Invalid project token.
            required:
            - error
            - message
            - status_code
    '429':
      description: Usage limit reached
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 429
              error:
                type: string
                example: Project Over Limit
              message:
                type: string
                example: Usage is over limit.
            required:
            - error
            - message
            - status_code
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 400
              error:
                type: string
                example: Bad Request
              message:
                type: string
                example: Backend did not understand your request.
            required:
            - error
            - message
            - status_code
    '404':
      description: Component not found
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 404
              error:
                type: string
                example: Not Found
              message:
                type: string
                example: The requested component has not been found.
            required:
            - error
            - message
            - status_code
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 500
              error:
                type: string
                example: Internal Server Error
              message:
                type: string
                example: An unexpected response was received from the backend.
            required:
            - error
            - message
            - status_code
    '418':
      description: IP has been auto-banned for extensive sending of requests after usage limit has been reached
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 418
              error:
                type: string
                example: Requested Banned
              message:
                type: string
                example: IP has been auto-banned for flooding.
            required:
            - error
            - message
            - status_code
  schemas:
    account_withdrawal_content:
      type: array
      items:
        type: object
        properties:
          tx_hash:
            type: string
            description: Hash of the transaction containing the withdrawal
          amount:
            type: string
            description: Withdrawal amount in Lovelaces
          tx_slot:
            type: integer
            description: Slot of the transaction containing the withdrawal
          block_time:
            type: integer
            description: Block creation time in UNIX time of the transaction containing the withdrawal
          block_height:
            type: integer
            description: Block height of the transaction containing the withdrawal
        required:
        - tx_hash
        - amount
        - tx_slot
        - block_time
        - block_height
      example:
      - tx_hash: 48a9625c841eea0dd2bb6cf551eabe6523b7290c9ce34be74eedef2dd8f7ecc5
        amount: '454541212442'
        tx_slot: 45093580
        block_time: 1646437200
        block_height: 6745358
      - tx_hash: 4230b0cbccf6f449f0847d8ad1d634a7a49df60d8c142bb8cc2dbc8ca03d9e34
        amount: '97846969'
        tx_slot: 48093580
        block_time: 1649033600
        block_height: 7126896
    account_addresses_total:
      type: object
      properties:
        stake_address:
          type: string
          description: Bech32 encoded stake address
          example: stake1u9l5q5jwgelgagzyt6nuaasefgmn8pd25c8e9qpeprq0tdcp0e3uk
        received_sum:
          type: array
          items:
            type: object
            description: The sum of all the UTXO per asset for all addresses associated with the account
            properties:
              unit:
                type: string
                format: Lovelace or concatenation of asset policy_id and hex-encoded asset_name
                description: The unit of the value
              quantity:
                type: string
                description: The quantity of the unit
            required:
            - unit
            - quantity
          example:
          - unit: lovelace
            quantity: '42000000'
          - unit: b0d07d45fe9514f80213f4020e5a61241458be626841cde717cb38a76e7574636f696e
            quantity: '12'
        sent_sum:
          type: array
          items:
            type: object
            description: The sum of all the UTXO per asset for all addresses associated with the account
            properties:
              unit:
                type: string
                format: Lovelace or concatenation of asset policy_id and hex-encoded asset_name
                description: The unit of the value
              quantity:
                type: string
                description: The quantity of the unit
            required:
            - unit
            - quantity
          example:
          - unit: lovelace
            quantity: '42000000'
          - unit: b0d07d45fe9514f80213f4020e5a61241458be626841cde717cb38a76e7574636f696e
            quantity: '12'
        tx_count:
          type: integer
          example: 12
          description: Count of all transactions for all addresses associated with the account
      required:
      - stake_address
      - received_sum
      - sent_sum
      - tx_count
    account_mir_content:
      type: array
      items:
        type: object
        properties:
          tx_hash:
            type: string
            description: Hash of the transaction containing the MIR
          amount:
            type: string
            description: MIR amount in Lovelaces
          tx_slot:
            type: integer
            description: Slot of the transaction containing the MIR
          block_time:
            type: integer
            description: Block creation time in UNIX time of the transaction containing the MIR
          block_height:
            type: integer
            description: Block height of the transaction containing the MIR
        required:
        - tx_hash
        - amount
        - tx_slot
        - block_time
        - block_height
      example:
      - tx_hash: 69705bba1d687a816ff5a04ec0c358a1f1ef075ab7f9c6cc2763e792581cec6d
        amount: '2193707473'
        tx_slot: 45093580
        block_time: 1646437200
        block_height: 6745358
      - tx_hash: baaa77b63d4d7d2bb3ab02c9b85978c2092c336dede7f59e31ad65452d510c13
        amount: '14520198574'
        tx_slot: 48093580
        block_time: 1649033600
        block_height: 7126896
    account_registration_content:
      type: array
      items:
        type: object
        properties:
          tx_hash:
            type: string
            description: Hash of the transaction containing the (de)registration certificate
          action:
            type: string
            enum:
            - registered
            - deregistered
            description: Action in the certificate
          tx_slot:
            type: integer
            description: Slot of the transaction containing the (de)registration certificate
          block_time:
            type: integer
            description: Block creation time in UNIX time of the transaction containing the (de)registration certificate
          block_height:
            type: integer
            description: Block height of the transaction containing the (de)registration certificate
        required:
        - tx_hash
        - action
        - tx_slot
        - block_time
        - block_height
      example:
      - tx_hash: 2dd15e0ef6e6a17841cb9541c27724072ce4d4b79b91e58432fbaa32d9572531
        action: registered
        tx_slot: 45093580
        block_time: 1646437200
        block_height: 6745358
      - tx_hash: 1a0570af966fb355a7160e4f82d5a80b8681b7955f5d44bec0dde628516157f0
        action: deregistered
        tx_slot: 48093580
        block_time: 1649033600
        block_height: 7126896
    account_delegation_content:
      type: array
      items:
        type: object
        properties:
          active_epoch:
            type: integer
            example: 210
            description: Epoch in which the delegation becomes active
          tx_hash:
            type: string
            description: Hash of the transaction containing the delegation
          amount:
            type: string
            description: Rewards for given epoch in Lovelaces
          pool_id:
            type: string
            description: Bech32 ID of pool being delegated to
          tx_slot:
            type: integer
            description: Slot of the transaction containing the delegation
          block_time:
            type: integer
            description: Block creation time in UNIX time of the transaction containing the delegation
          block_height:
            type: integer
            description: Block height of the transaction containing the delegation
        required:
        - active_epoch
        - tx_hash
        - amount
        - pool_id
        - tx_slot
        - block_time
        - block_height
      example:
      - active_epoch: 210
        tx_hash: 2dd15e0ef6e6a17841cb9541c27724072ce4d4b79b91e58432fbaa32d9572531
        amount: '12695385'
        pool_id: pool1pu5jlj4q9w9jlxeu370a3c9myx47md5j5m2str0naunn2q3lkdy
        tx_slot: 45093580
        block_time: 1646437200
        block_height: 6745358
      - active_epoch: 242
        tx_hash: 1a0570af966fb355a7160e4f82d5a80b8681b7955f5d44bec0dde628516157f0
        amount: '12691385'
        pool_id: pool1kchver88u3kygsak8wgll7htr8uxn5v35lfrsyy842nkscrzyvj
        tx_slot: 48093580
        block_time: 1649033600
        block_height: 7126896
    account_addresses_content:
      type: array
      items:
        type: object
        properties:
          address:
            type: string
            description: Address associated with the stake key
        required:
        - address
      example:
      - address: addr1qx2kd28nq8ac5prwg32hhvudlwggpgfp8utlyqxu6wqgz62f79qsdmm5dsknt9ecr5w468r9ey0fxwkdrwh08ly3tu9sy0f4qd
      - address: addr1qys3czp8s9thc6u2fqed9yq3h24nyw28uk0m6mkgn9dkckjf79qsdmm5dsknt9ecr5w468r9ey0fxwkdrwh08ly3tu9suth4w4
      - address: addr1q8j55h253zcvl326sk5qdt2n8z7eghzspe0ekxgncr796s2f79qsdmm5dsknt9ecr5w468r9ey0fxwkdrwh08ly3tu9sjmd35m
      - address: addr1q8f7gxrprank3drhx8k5grlux7ene0nlwun8y9thu8mc3yjf79qsdmm5dsknt9ecr5w468r9ey0fxwkdrwh08ly3tu9sls6vnt
    account_addresses_assets:
      type: array
      items:
        type: object
        description: The sum of all assets of all addresses associated with a given account
        properties:
          unit:
            type: string
            format: Concatenation of asset policy_id and hex-encoded asset_name
            description: The unit of the value
          quantity:
            type: string
            description: The quantity of the unit
        required:
        - unit
        - quantity
      example:
      - unit: d5e6bf0500378d4f0da4e8dde6becec7621cd8cbf5cbb9b87013d4cc537061636542756433343132
        quantity: '1'
      - unit: b0d07d45fe9514f80213f4020e5a61241458be626841cde717cb38a76e7574636f696e
        quantity: '125'
    account_history_content:
      type: array
      items:
        type: object
        properties:
          active_epoch:
            type: integer
            example: 210
            description: Epoch in which the stake was active
          amount:
            type: string
            description: Stake amount in Lovelaces
          pool_id:
            type: string
            description: Bech32 ID of pool being delegated to
        required:
        - active_epoch
        - amount
        - pool_id
      example:
      - active_epoch: 210
        amount: '12695385'
        pool_id: pool1pu5jlj4q9w9jlxeu370a3c9myx47md5j5m2str0naunn2q3lkdy
      - active_epoch: 211
        amount: '22695385'
        pool_id: pool1pu5jlj4q9w9jlxeu370a3c9myx47md5j5m2str0naunn2q3lkdy
    account_utxo_content:
      type: array
      items:
        type: object
        properties:
          address:
            type: string
            description: Bech32 encoded addresses
            example: addr1qxqs59lphg8g6qndelq8xwqn60ag3aeyfcp33c2kdp46a09re5df3pzwwmyq946axfcejy5n4x0y99wqpgtp2gd0k09qsgy6pz
          tx_hash:
            type: string
            description: Transaction hash of the UTXO
          tx_index:
            type: integer
            deprecated: true
            description: UTXO index in the transaction
          output_index:
            type: integer
            description: UTXO index in the transaction
          amount:
            type: array
            items:
              type: object
              description: The sum of all the UTXO per asset
              properties:
                unit:
                  type: string
                  format: Lovelace or concatenation of asset policy_id and hex-encoded asset_name
                  description: The unit of the value
                quantity:
                  type: string
                  description: The quantity of the unit
              required:
              - unit
              - quantity
          block:
            type: string
            description: Block hash of the UTXO
          data_hash:
            type:
            - string
            - 'null'
            description: The hash of the transaction output datum
          inline_datum:
            type:
            - string
            - 'null'
            description: CBOR encoded inline datum
            example: 19a6aa
          reference_script_hash:
            type:
            - string
            - 'null'
            description: The hash of the reference script of the output
            example: 13a3efd825703a352a8f71f4e2758d08c28c564e8dfcce9f77776ad1
        required:
        - address
        - tx_hash
        - tx_index
        - output_index
        - amount
        - block
        - data_hash
        - inline_datum
        - reference_script_hash
      example:
      - address: addr1qxqs59lphg8g6qndelq8xwqn60ag3aeyfcp33c2kdp46a09re5df3pzwwmyq946axfcejy5n4x0y99wqpgtp2gd0k09qsgy6pz
        tx_hash: 39a7a284c2a0948189dc45dec670211cd4d72f7b66c5726c08d9b3df11e44d58
        output_index: 0
        amount:
        - unit: lovelace
          quantity: '42000000'
        block: 7eb8e27d18686c7db9a18f8bbcfe34e3fed6e047afaa2d969904d15e934847e6
        data_hash: 9e478573ab81ea7a8e31891ce0648b81229f408d596a3483e6f4f9b92d3cf710
        inline_datum: null
        reference_script_hash: null
      - address: addr1qxqs59lphg8g6qndelq8xwqn60ag3aeyfcp33c2kdp46a09re5df3pzwwmyq946axfcejy5n4x0y99wqpgtp2gd0k09qsgy6pz
        tx_hash: 4c4e67bafa15e742c13c592b65c8f74c769cd7d9af04c848099672d1ba391b49
        output_index: 0
        amount:
        - unit: lovelace
          quantity: '729235000'
        block: 953f1b80eb7c11a7ffcd67cbd4fde66e824a451aca5a4065725e5174b81685b7
        data_hash: null
        inline_datum: null
        reference_script_hash: null
      - address: addr1qxqs59lphg8g6qndelq8xwqn60ag3aeyfcp33c2kdp46a09re5df3pzwwmyq946axfcejy5n4x0y99wqpgtp2gd0k09qsgy6pz
        tx_hash: 768c63e27a1c816a83dc7b07e78af673b2400de8849ea7e7b734ae1333d100d2
        output_index: 1
        amount:
        - unit: lovelace
          quantity: '42000000'
        - unit: b0d07d45fe9514f80213f4020e5a61241458be626841cde717cb38a76e7574636f696e
          quantity: '12'
        block: 5c571f83fe6c784d3fbc223792627ccf0eea96773100f9aedecf8b1eda4544d7
        data_hash: null
        inline_datum: null
        reference_script_hash: null
    account_content:
      type: object
      properties:
        stake_address:
          type: string
          example: stake1ux3g2c9dx2nhhehyrezyxpkstartcqmu9hk63qgfkccw5rqttygt7
          description: Bech32 stake address
        active:
          type: boolean
          example: true
          description: Delegation state of the account. **Note:** For registration state, use the `registered` field instead.
        registered:
          type: boolean
          example: true
          description: Registration state of an account
        active_epoch:
          type:
          - integer
          - 'null'
          example: 412
          description: Epoch of the most recent action - registration or deregistration
        controlled_amount:
          type: string
          example: '619154618165'
          description: Balance of the account in Lovelaces
        rewards_sum:
          type: string
          example: '319154618165'
          description: Sum of all rewards for the account in the Lovelaces
        withdrawals_sum:
          type: string
          example: '12125369253'
          description: Sum of all the withdrawals for the account in Lovelaces
        reserves_sum:
          type: string
          example: '319154618165'
          description: Sum of all  funds from reserves for the account in the Lovelaces
        treasury_sum:
          type: string
          example: '12000000'
          description: Sum of all funds from treasury for the account in the Lovelaces
        withdrawable_amount:
          type: string
          example: '319154618165'
          description: Sum of available rewards that haven't been withdrawn yet for the account in the Lovelaces
        pool_id:
          type:
          - string
          - 'null'
          example: pool1pu5jlj4q9w9jlxeu370a3c9myx47md5j5m2str0naunn2q3lkdy
          description: Bech32 pool ID to which this account is delegated
        drep_id:
          type:
          - string
          - 'null'
          example: drep15cfxz9exyn5rx0807zvxfrvslrjqfchrd4d47kv9e0f46uedqtc
          description: Bech32 drep ID to which this account is delegated
      required:
      - stake_address
      - active
      - registered
      - active_epoch
      - controlled_amount
      - rewards_sum
      - withdrawals_sum
      - reserves_sum
      - treasury_sum
      - withdrawable_amount
      - pool_id
      - drep_id
    account_reward_content:
      type: array
      items:
        type: object
        properties:
          epoch:
            type: integer
            description: Epoch of the associated reward
          amount:
            type: string
            description: Rewards for given epoch in Lovelaces
          pool_id:
            type: string
            description: Bech32 pool ID being delegated to
          type:
            type: string
            enum:
            - leader
            - member
            - pool_deposit_refund
            description: Type of the reward
        required:
        - epoch
        - amount
        - pool_id
        - type
      example:
      - epoch: 215
        amount: '12695385'
        pool_id: pool1pu5jlj4q9w9jlxeu370a3c9myx47md5j5m2str0naunn2q3lkdy
        type: member
      - epoch: 216
        amount: '3586329'
        pool_id: pool1pu5jlj4q9w9jlxeu370a3c9myx47md5j5m2str0naunn2q3lkdy
        type: member
      - epoch: 217
        amount: '1'
        pool_id: pool1pu5jlj4q9w9jlxeu370a3c9myx47md5j5m2str0naunn2q3lkdy
        type: member
      - epoch: 217
        amount: '1337'
        pool_id: pool1cytwr0n7eas6du2h2xshl8ypa1yqr18f0erlhhjcuczysiunjcs
        type: leader
      - epoch: 218
        amount: '1395265'
        pool_id: pool1pu5jlj4q9w9jlxeu370a3c9myx47md5j5m2str0naunn2q3lkdy
        type: member
      - epoch: 218
        amount: '500000000'
        pool_id: pool1cytwr0n7eas6du2h2xshl8ypa1yqr18f0erlhhjcuczysiunjcs
        type: pool_deposit_refund
    account_transactions_content:
      type: array
      items:
        type: object
        properties:
          address:
            type: string
            description: Bech32 address
          tx_hash:
            type: string
            description: Hash of the transaction
          tx_index:
            type: integer
            description: Transaction index within the block
          block_height:
            type: integer
            description: Block height
          block_time:
            type: integer
            description: Block creation time in UNIX time
        required:
        - address
        - tx_hash
        - tx_index
        - block_height
        - block_time
      example:
      - address: addr1q8zsjx7vxkl4esfejafhxthyew8c54c9ch95gkv3nz37sxrc9ty742qncmffaesxqarvqjmxmy36d9aht2duhmhvekgq3jd3w2
        tx_hash: bd78e0e73fb1691f08746a331bd764d11552c3a36ef766d4f1a3bbdc7f29918d
        tx_index: 34
        block_height: 7900364
        block_time: 1666114079
      - address: addr1q8zsjx7vxkl4esfejafhxthyew8c54c9ch95gkv3nz37sxrc9ty742qncmffaesxqarvqjmxmy36d9aht2duhmhvekgq3jd3w2
        tx_hash: 67e9a201bc08a92bcc6f447a4ed032300d933545ccd7f1da94ec1e8dbeb4a696
        tx_index: 6
        block_height: 7900557
        block_time: 1666118180
      - address: addr1qxrrzqsqnzqx3p8sxxsry936h6c78ml4rdl224f33l7pmcnc9ty742qncmffaesxqarvqjmxmy36d9aht2duhmhvekgqr735lq
        tx_hash: 67e9a201bc08a92bcc6f447a4ed032300d933545ccd7f1da94ec1e8dbeb4a696
        tx_index: 6
        block_height: 7900557
        block_time: 1666118180
  securitySchemes:
    project_id:
      type: apiKey
      in: header
      name: project_id
      description: 'There are multiple token types available based on network you choose

        when creating a Blockfrost a project, for a list of token types

        see available networks.

        '
